version: "3"

services:
  wadapi.service:
    container_name: wadapi.service
    ports:
      - 1313:80
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/logs:/var/log/nginx
  php.local:
    container_name: wadapi.service.php
    restart: always
    build:
      context: .
      dockerfile: docker/php/Dockerfile
  messaging.local:
    container_name: wadapi.service.messaging
    restart: always
    build:
      context: .
      dockerfile: docker/messaging/Dockerfile
